### ISSUE TITLE
ElapsedTime in bot state is not calculated correctly.

### ISSUE THREAD

**Issue by S-Rabe** [EntelectChallenge/2023-Cy-Fi#5]
Hi There,

I seems that the ElapsedTime value in the BotState is not being calculated correctly.
The calculation of the value being sent to bots is done in BotStateDTO.cs:
https://github.com/EntelectChallenge/2023-Cy-Fi/blob/ebf159cb845114037f5cfb8a3e0205e532c47129/2023-CyFi/CyFi/Runner/BotStateDTO.cs#L33

This calculation uses the Start and End values as defined in HeroEntity.cs:
https://github.com/EntelectChallenge/2023-Cy-Fi/blob/ebf159cb845114037f5cfb8a3e0205e532c47129/2023-CyFi/CyFi/Entity/HeroEntity.cs#L18-L19

The Start value on the hero entity is set when a bot gets registered:
https://github.com/EntelectChallenge/2023-Cy-Fi/blob/ebf159cb845114037f5cfb8a3e0205e532c47129/2023-CyFi/CyFi/CyFiEngine.cs#L82

The End value is never given a value after being created as part of HeroEntity. 
This leads to the following situation when trying to calculate ElapsedTime:

![image](https://github.com/EntelectChallenge/2023-Cy-Fi/assets/35628382/779cc975-7be9-4643-b4f7-9e58fb34e4d9)

One possible place to update the End value on HeroEntities is in the root state Update function:
https://github.com/EntelectChallenge/2023-Cy-Fi/blob/ebf159cb845114037f5cfb8a3e0205e532c47129/2023-CyFi/CyFi/RootState/CyFiState.cs#L40-L54

Another possible place to update the End value is in the GameLoop function where the BotStateDTO is created:
https://github.com/EntelectChallenge/2023-Cy-Fi/blob/ebf159cb845114037f5cfb8a3e0205e532c47129/2023-CyFi/CyFi/CyFiEngine.cs#L124-L139

Alternatively, the End value could be removed from HeroEntities since it is not used anywhere in the program except to calculate ElapsedTime. Instead, the LastUpdated value from the Bot itself could be used since it gets updated every tick:
![image](https://github.com/EntelectChallenge/2023-Cy-Fi/assets/35628382/467e7939-a0e6-43d4-947d-470366635a86)

Depending on how / where you want to handle this I can put together a PR.

**Comment by ZJouba** [comment]
Thanks S-Rabe. Let's go with the `LastUpdated` approach
